require 'faker'

Comment.destroy_all
User.destroy_all
Post.destroy_all
Tag.destroy_all
Like.destroy_all

# USERS
ud = User.create!({ email: 'demo@demo.com', password: '12345678', username: 'demo_user19' })
admin = User.create!({ email: 'admin@demo.com', password: '12345678', username: 'admin', admin: true })
u1 = User.create!({ email: 'user1@demo.com', password: '12345678', username: 'itsK' })
u2 = User.create!({ email: 'user2@demo.com', password: '12345678', username: 'feltfanatic' })
u3 = User.create!({ email: 'user3@demo.com', password: '12345678', username: 'ZRobot' })
u4 = User.create!({ email: 'user4@demo.com', password: '12345678', username: 'hauntedHeather' })
u5 = User.create!({ email: 'user5@demo.com', password: '12345678', username: 'AnnaMay' })
u6 = User.create!({ email: 'user6@demo.com', password: '12345678', username: 'bestie' })
u7 = User.create!({ email: 'user7@demo.com', password: '12345678', username: 'youAlreadyKnow' })
u8 = User.create!({ email: 'user8@demo.com', password: '12345678', username: 'zim77' })
u9 = User.create!({ email: 'user9@demo.com', password: '12345678', username: 'worthy1' })
u10 = User.create!({ email: 'user10@demo.com', password: '12345678', username: 'yoyoWizard' })

# USER PROFILE PICS
u1.profile_pic.attach(io: EzDownload.open('https://s3.amazonaws.com/stellar-dev/user1.jpg'), filename: 'seed')
u2.profile_pic.attach(io: EzDownload.open('https://s3.amazonaws.com/stellar-dev/user2.jpg'), filename: 'seed')
u3.profile_pic.attach(io: EzDownload.open('https://s3.amazonaws.com/stellar-dev/user3.jpg'), filename: 'seed')
u4.profile_pic.attach(io: EzDownload.open('https://s3.amazonaws.com/stellar-dev/user4.jpg'), filename: 'seed')
u5.profile_pic.attach(io: EzDownload.open('https://s3.amazonaws.com/stellar-dev/user5.jpg'), filename: 'seed')
u6.profile_pic.attach(io: EzDownload.open('https://s3.amazonaws.com/stellar-dev/user6.jpg'), filename: 'seed')
u7.profile_pic.attach(io: EzDownload.open('https://s3.amazonaws.com/stellar-dev/user7.jpg'), filename: 'seed')
u8.profile_pic.attach(io: EzDownload.open('https://s3.amazonaws.com/stellar-dev/user8.jpg'), filename: 'seed')
u9.profile_pic.attach(io: EzDownload.open('https://s3.amazonaws.com/stellar-dev/user9.jpg'), filename: 'seed')
u10.profile_pic.attach(io: EzDownload.open('https://s3.amazonaws.com/stellar-dev/user10.jpg'), filename: 'seed')

# TAGS
t1 = Tag.create!({subject: '#food'})
t2 = Tag.create!({subject: '#anime'})
t3 = Tag.create!({subject: '#trails'})
t4 = Tag.create!({subject: '#running'})
t5 = Tag.create!({subject: '#gaming'})
t6 = Tag.create!({subject: '#music'})
t7 = Tag.create!({subject: '#life'})
t8 = Tag.create!({subject: '#reading'})
t9 = Tag.create!({subject: '#coffee'})

# POSTS 
p1 = Post.create(title: Faker::Book.title, body: Faker::Quote.famous_last_words, tag_ids: [t1.id, t2.id, t3.id], user_id: u1.id)
p1.media.attach(io: EzDownload.open('https://s3.amazonaws.com/stellar-dev/anime1.gif'), filename: 'seed')
Post.create(title: Faker::Book.title, body: Faker::Hipster.paragraph_by_chars, tag_ids: [t8.id, t9.id], user_id: u10.id)
p2 = Post.create(title: Faker::Book.title, body: Faker::Quote.matz, tag_ids: [t4.id, t5.id, t6.id], user_id: u2.id)
p2.media.attach(io: EzDownload.open('https://s3.amazonaws.com/stellar-dev/books2.jpg'), filename: 'seed')
Post.create(title: Faker::Book.title, body: Faker::Quote.robin, tag_ids: [t7.id, t8.id, t9.id], user_id: u3.id)
p3 = Post.create(title: Faker::Book.title, body: Faker::Quote.robin, tag_ids: [t7.id, t8.id, t9.id], user_id: u3.id)
p3.media.attach(io: EzDownload.open('https://s3.amazonaws.com/stellar-dev/cafe1.jpg'), filename: 'seed')
Post.create(title: Faker::Book.title, body: Faker::Quote.matz, tag_ids: [t9.id, t1.id, t2.id, t3.id], user_id: u8.id)
p4 = Post.create(title: Faker::Book.title, body: Faker::Quote.singular_siegler, tag_ids: [t1.id, t2.id], user_id: u4.id)
p4.media.attach(io: EzDownload.open('https://s3.amazonaws.com/stellar-dev/food1.jpg'), filename: 'seed')
Post.create(title: Faker::Book.title, body: Faker::Quote.famous_last_words, tag_ids: [t7.id, t8.id], user_id: u7.id)
p5 = Post.create(title: Faker::Book.title, body: Faker::Quote.yoda, tag_ids: [t3.id, t4.id], user_id: u5.id)
p5.media.attach(io: EzDownload.open('https://s3.amazonaws.com/stellar-dev/gaming1.jpg'), filename: 'seed')
Post.create(title: Faker::Book.title, body: Faker::Hipster.paragraph_by_chars, tag_ids: [t8.id, t9.id], user_id: u10.id)
p6 = Post.create(title: Faker::Book.title, body: Faker::Hipster.paragraph_by_chars, tag_ids: [t5.id, t6.id], user_id: u6.id)
p6.media.attach(io: EzDownload.open('https://s3.amazonaws.com/stellar-dev/music1.jpg'), filename: 'seed')
Post.create(title: Faker::Book.title, body: Faker::Quote.robin, tag_ids: [t4.id, t5.id, t6.id, t7.id], user_id: u9.id)
p7 = Post.create(title: Faker::Book.title, body: Faker::Quote.famous_last_words, tag_ids: [t7.id, t8.id], user_id: u7.id)
p7.media.attach(io: EzDownload.open('https://s3.amazonaws.com/stellar-dev/running1.jpg'), filename: 'seed')
Post.create(title: Faker::Book.title, body: Faker::Quote.matz, tag_ids: [t9.id, t1.id, t2.id, t3.id], user_id: u8.id)
p8 = Post.create(title: Faker::Book.title, body: Faker::Quote.matz, tag_ids: [t9.id, t1.id, t2.id, t3.id], user_id: u8.id)
p8.media.attach(io: EzDownload.open('https://s3.amazonaws.com/stellar-dev/trail1.jpg'), filename: 'seed')
Post.create(title: Faker::Book.title, body: Faker::Quote.famous_last_words, tag_ids: [t7.id, t8.id], user_id: u7.id)
p9 = Post.create(title: Faker::Book.title, body: Faker::Quote.robin, tag_ids: [t4.id, t5.id, t6.id, t7.id], user_id: u9.id)
p9.media.attach(io: EzDownload.open('https://s3.amazonaws.com/stellar-dev/anime2.gif'), filename: 'seed')
Post.create(title: Faker::Book.title, body: Faker::Hipster.paragraph_by_chars, tag_ids: [t5.id, t6.id], user_id: u6.id)
p10 = Post.create(title: Faker::Book.title, body: Faker::Hipster.paragraph_by_chars, tag_ids: [t8.id, t9.id], user_id: u10.id)
p10.media.attach(io: EzDownload.open('https://s3.amazonaws.com/stellar-dev/cafe2.jpg'), filename: 'seed')
Post.create(title: Faker::Book.title, body: Faker::Quote.yoda, tag_ids: [t3.id, t4.id], user_id: u5.id)
p11 = Post.create(title: Faker::Book.title, body: Faker::Quote.famous_last_words, tag_ids: [t1.id, t2.id, t3.id], user_id: u1.id)
p11.media.attach(io: EzDownload.open('https://s3.amazonaws.com/stellar-dev/anime1.gif'), filename: 'seed')
Post.create(title: Faker::Book.title, body: Faker::Quote.singular_siegler, tag_ids: [t1.id, t2.id], user_id: u4.id)
p12 = Post.create(title: Faker::Book.title, body: Faker::Quote.matz, tag_ids: [t4.id, t5.id, t6.id], user_id: u2.id)
p12.media.attach(io: EzDownload.open('https://s3.amazonaws.com/stellar-dev/food2.jpg'), filename: 'seed')
Post.create(title: Faker::Book.title, body: Faker::Quote.robin, tag_ids: [t7.id, t8.id, t9.id], user_id: u3.id)
p13 = Post.create(title: Faker::Book.title, body: Faker::Quote.robin, tag_ids: [t7.id, t8.id, t9.id], user_id: u3.id)
p13.media.attach(io: EzDownload.open('https://s3.amazonaws.com/stellar-dev/gaming2.jpg'), filename: 'seed')
Post.create(title: Faker::Book.title, body: Faker::Quote.matz, tag_ids: [t4.id, t5.id, t6.id], user_id: u2.id)
p14 = Post.create(title: Faker::Book.title, body: Faker::Quote.singular_siegler, tag_ids: [t1.id, t2.id], user_id: u4.id)
p14.media.attach(io: EzDownload.open('https://s3.amazonaws.com/stellar-dev/running2.jpg'), filename: 'seed')
Post.create(title: Faker::Book.title, body: Faker::Quote.famous_last_words, tag_ids: [t1.id, t2.id, t3.id], user_id: u1.id)
p15 = Post.create(title: Faker::Book.title, body: Faker::Quote.yoda, tag_ids: [t3.id, t4.id], user_id: u5.id)
p15.media.attach(io: EzDownload.open('https://s3.amazonaws.com/stellar-dev/trail2.jpg'), filename: 'seed')
Post.create(title: Faker::Book.title, body: Faker::Hipster.paragraph_by_chars, tag_ids: [t8.id, t9.id], user_id: u10.id)
p16 = Post.create(title: Faker::Book.title, body: Faker::Hipster.paragraph_by_chars, tag_ids: [t5.id, t6.id], user_id: u6.id)
p16.media.attach(io: EzDownload.open('https://s3.amazonaws.com/stellar-dev/cafe3.jpg'), filename: 'seed')
Post.create(title: Faker::Book.title, body: Faker::Quote.robin, tag_ids: [t4.id, t5.id, t6.id, t7.id], user_id: u9.id)
p17 = Post.create(title: Faker::Book.title, body: Faker::Quote.famous_last_words, tag_ids: [t7.id, t8.id], user_id: u7.id)
p17.media.attach(io: EzDownload.open('https://s3.amazonaws.com/stellar-dev/food3.jpg'), filename: 'seed')
Post.create(title: Faker::Book.title, body: Faker::Quote.matz, tag_ids: [t9.id, t1.id, t2.id, t3.id], user_id: u8.id)
p18 = Post.create(title: Faker::Book.title, body: Faker::Quote.matz, tag_ids: [t9.id, t1.id, t2.id, t3.id], user_id: u8.id)
p18.media.attach(io: EzDownload.open('https://s3.amazonaws.com/stellar-dev/music3.jpg'), filename: 'seed')
Post.create(title: Faker::Book.title, body: Faker::Quote.famous_last_words, tag_ids: [t7.id, t8.id], user_id: u7.id)
p19 = Post.create(title: Faker::Book.title, body: Faker::Quote.robin, tag_ids: [t4.id, t5.id, t6.id, t7.id], user_id: u9.id)
p19.media.attach(io: EzDownload.open('https://s3.amazonaws.com/stellar-dev/running3.gif'), filename: 'seed')
Post.create(title: Faker::Book.title, body: Faker::Hipster.paragraph_by_chars, tag_ids: [t5.id, t6.id], user_id: u6.id)
p20 = Post.create(title: Faker::Book.title, body: Faker::Hipster.paragraph_by_chars, tag_ids: [t8.id, t9.id], user_id: u10.id)
p20.media.attach(io: EzDownload.open('https://s3.amazonaws.com/stellar-dev/trail3.jpg'), filename: 'seed')
Post.create(title: Faker::Book.title, body: Faker::Quote.yoda, tag_ids: [t3.id, t4.id], user_id: u5.id)
p21 = Post.create(title: Faker::Book.title, body: Faker::Quote.famous_last_words, tag_ids: [t1.id, t2.id, t3.id], user_id: u1.id)
p21.media.attach(io: EzDownload.open('https://s3.amazonaws.com/stellar-dev/cafe4.gif'), filename: 'seed')
Post.create(title: Faker::Book.title, body: Faker::Quote.singular_siegler, tag_ids: [t1.id, t2.id], user_id: u4.id)
p22 = Post.create(title: Faker::Book.title, body: Faker::Quote.matz, tag_ids: [t4.id, t5.id, t6.id], user_id: u2.id)
p22.media.attach(io: EzDownload.open('https://s3.amazonaws.com/stellar-dev/food4.jpg'), filename: 'seed')
Post.create(title: Faker::Book.title, body: Faker::Quote.robin, tag_ids: [t7.id, t8.id, t9.id], user_id: u3.id)
p23 = Post.create(title: Faker::Book.title, body: Faker::Quote.robin, tag_ids: [t7.id, t8.id, t9.id], user_id: u3.id)
p23.media.attach(io: EzDownload.open('https://s3.amazonaws.com/stellar-dev/music4.jpg'), filename: 'seed')
Post.create(title: Faker::Book.title, body: Faker::Quote.matz, tag_ids: [t4.id, t5.id, t6.id], user_id: u2.id)
p24 = Post.create(title: Faker::Book.title, body: Faker::Quote.singular_siegler, tag_ids: [t1.id, t2.id], user_id: u4.id)
p24.media.attach(io: EzDownload.open('https://s3.amazonaws.com/stellar-dev/running4.jpg'), filename: 'seed')
Post.create(title: Faker::Book.title, body: Faker::Quote.famous_last_words, tag_ids: [t1.id, t2.id, t3.id], user_id: u1.id)
p25 = Post.create(title: Faker::Book.title, body: Faker::Quote.yoda, tag_ids: [t3.id, t4.id], user_id: u5.id)
p25.media.attach(io: EzDownload.open('https://s3.amazonaws.com/stellar-dev/trail4.jpg'), filename: 'seed')
Post.create(title: Faker::Book.title, body: Faker::Hipster.paragraph_by_chars, tag_ids: [t8.id, t9.id], user_id: u10.id)
p26 = Post.create(title: Faker::Book.title, body: Faker::Hipster.paragraph_by_chars, tag_ids: [t5.id, t6.id], user_id: u6.id)
p26.media.attach(io: EzDownload.open('https://s3.amazonaws.com/stellar-dev/running5.jpg'), filename: 'seed')
Post.create(title: Faker::Book.title, body: Faker::Quote.matz, tag_ids: [t9.id, t1.id, t2.id, t3.id], user_id: u8.id)
p27 = Post.create(title: Faker::Book.title, body: Faker::Quote.famous_last_words, tag_ids: [t7.id, t8.id], user_id: u7.id)
p27.media.attach(io: EzDownload.open('https://s3.amazonaws.com/stellar-dev/trail5.jpg'), filename: 'seed')
Post.create(title: Faker::Book.title, body: Faker::Quote.robin, tag_ids: [t4.id, t5.id, t6.id, t7.id], user_id: u9.id)